apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-hello-deployment
spec:
  selector:
    matchLabels:
      app: node-hello
  replicas: 2
  template:
    metadata:
      labels:
        app: node-hello
    spec:
      containers:
        - name: node-hello
          image: node-hello
          ports:
            - containerPort: 3000
          imagePullPolicy: Never
