apiVersion: v1
kind: Service
metadata:
  name: sw-service
spec:
  selector:
    app: node-hello
  type: LoadBalancer 
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
      nodePort: 31000